'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Category
    
    '''<summary>
    '''lblBreadCrumb1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBreadCrumb1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBreadCrumb2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBreadCrumb2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProductList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductList As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SqlProductList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlProductList As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''rpProductList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpProductList As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''lblParentCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParentCategory As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMainCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMainCategories As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SqlSubCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlSubCategories As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''rpSubCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpSubCategory As Global.System.Web.UI.WebControls.Repeater
End Class
